apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-app
  labels:
    app: parking-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: parking-app
  template:
    metadata:
      labels:
        app: parking-app
    spec:
      containers:
        - name: parking-container
          image: bohuang910407/fastapi-parking:latest # Use the local registry image
          ports:
            - containerPort: 8000 # Exposing port 8000 since FastAPI runs on this port
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_PORT
            - name: DATABASE_ENV
              value: "k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: parking-service
spec:
  selector:
    app: parking-app
  ports:
    - protocol: TCP
      port: 8000        # The port the service will be exposed on within the cluster
      targetPort: 8000 # The port the FastAPI app listens on
  type: ClusterIP     # Internal service (since ingress will expose it externally)