apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring  # Specifies the namespace where the secret will be created
type: Opaque
data:
  GRAFANA_USER: YWRtaW4=  # base64 encoded "admin"
  GRAFANA_PASSWORD: YWRtaW5BZG1pbjEyMyE=  # base64 encoded "adminAdmin123!"
