name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  check-code:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only run this job on push events

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8  # Install Black and Flake8

      - name: Run Black
        run: |
          black --check .  # Check code formatting

      - name: Run Flake8
        run: |
          flake8  # Run Flake8 for linting

  run-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Only run this job on pull requests to main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install all dependencies

      - name: Run tests
        run: |
          pytest  # Run pytest to execute tests
